DAMAGE_TABLE = {
    (1, 1): (-3, -3, None, False, False, False, False),
    (1, 2): (-2, -3, None, False, False, False, False),
    (1, 3): (0, -3, "Первый игрок сбивает подпрыгнувшего", False, False, False, False),
    (1, 4): (-5, 0, "Нога длиннее руки и достигает цели раньше", False, False, False, False),
    (1, 5): (-4, 0, "Нога длиннее руки и достигает цели раньше", False, False, False, False),
    (1, 6): (0, -3, "Первый игрок сбивает подпрыгнувшего", False, False, False, False),
    (1, 7): (0, 0, None, False, False, False, False),
    (1, 8): (-6, 0, "Удар первого игрока не успевает достичь цели", False, False, False, False),
    (1, 9): (-1, 0, "Первый игрок падает и не успевает нанести удар", False, False, False, False),
    (1, 10): (-2, 0, "Рука перехватывается и происходит бросок", False, False, False, False),
    (1, 11): (0, -3, None, False, False, False, False),
    (1, 12): (0, -3, None, False, False, False, False),

    (2, 1): (-3, -2, None, False, False, False, False),
    (2, 2): (-2, -2, None, False, False, False, False),
    (2, 3): (-3, 0, "Удар по корпусу не достигает цели", False, False, False, False),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, 0, None, False, False, False, False),
    (2, 6): (-5, 0, None, False, False, False, False),
    (2, 7): (0, 0, None, False, False, False, False),
    (2, 8): (0, -2, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, False, False),
    (2, 9): (-1, 0, None, False, False, False, False),
    (2, 10): (-2, 0, None, False, False, False, False),
    (2, 11): (0, -2, None, False, False, False, False),
    (2, 12): (0, -2, None, False, False, False, False),

    (3, 1): (-3, 0, None, False, False, False, False),
    (3, 2): (0, -3, None, False, False, False, False),
    (3, 3): (-3, -3, None, False, False, False, False),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -3, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, 0, "Нога длиннее руки", False, False, False, False),
    (3, 7): (0, 0, None, False, False, False, False),
    (3, 8): (-6, 0, "Подпрынувший просто отлетает от удара ногой с разворота", False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (0, -3, "Подпрыгнувший пробивается ударом через захват и его нельзя бросить", False, False, False, False),
    (3, 11): (0, -3, None, False, False, False, False),
    (3, 12): (0, -3, None, False, False, False, False),


    (4, 1): (0, -5, None, False, False, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, None, False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-2, 0, "Нога захватывается и производится бросок", False, False, False, False),
    (4, 11): (0, -5, None, False, False, False, False),
    (4, 12): (0, -5, None, False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (0, -4, None, False, False, False, False),
    (5, 3): (-3, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-2, 0, "Нога захватывается и производится бросок", False, False, False, False),
    (5, 11): (0, -4, None, False, False, False, False),
    (5, 12): (0, -4, None, False, False, False, False),


    (6, 1): (-3, 0, None, False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (0, -5, None, False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (0, -6, None, False, False, False, False),
    (6, 11): (0, -6, None, False, False, False, False),
    (6, 12): (0, -6, None, False, False, False, False),


    (7, 1): (0, 0, None, False, False, False, False),
    (7, 2): (0, 0, None, False, False, False, False),
    (7, 3): (0, 0, None, False, False, False, False),
    (7, 4): (0, 0, None, False, False, False, False),
    (7, 5): (0, 0, None, False, False, False, False),
    (7, 6): (0, 0, None, False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, 0, None, False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника", False, False, False, False),
    (7, 10): (-2, 0, "Происходит захват за блок и бросок", False, False, False, False),
    (7, 11): (0, 0, None, False, False, False, False),
    (7, 12): (0, 0, None, False, False, False, False),

    (8, 1): (0, -6, None, False, False, False, False),
    (8, 2): (-2, 0, None, False, False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (0, -6, "Не удается перехватить разворачивающегося противника, происходит удар, бросок не получается", False, False, False, False),
    (8, 11): (0, -6, None, False, False, False, False),
    (8, 12): (0, -6, None, False, False, False, False),

    (9, 1): (0, -1, None, False, False, False, False),
    (9, 2): (0, -1, None, False, False, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, None, False, False, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Не получается захватить того, кто делает подсечку", False, False, False, False),
    (9, 11): (0, -1, None, False, False, False, False),
    (9, 12): (0, -1, None, False, False, False, False),

    (10, 1): (0, -2, None, False, False, False, False),
    (10, 2): (0, -2, None, False, False, False, False),
    (10, 3): (-3, 0, None, False, False, False, False),
    (10, 4): (0, -2, None, False, False, False, False),
    (10, 5): (0, -2, None, False, False, False, False),
    (10, 6): (-5, 0, None, False, False, False, False),
    (10, 7): (0, -2, None, False, False, False, False),
    (10, 8): (-6, 0, None, False, False, False, False),
    (10, 9): (-1, 0, None, False, False, False, False),
    (10, 10): (0, 0, "Противники производят захват, сильно тянут и расцепляются, атаки не происходит", False, False, False, False),
    (10, 11): (0, -2, None, False, False, False, False),
    (10, 12): (0, -2, None, False, False, False, False),


    (11, 1): (-3, 0, None, False, False, False, False),
    (11, 2): (-2, 0, None, False, False, False, False),
    (11, 3): (-3, 0, None, False, False, False, False),
    (11, 4): (-5, 0, None, False, False, False, False),
    (11, 5): (-4, 0, None, False, False, False, False),
    (11, 6): (-5, 0, None, False, False, False, False),
    (11, 7): (0, 0, None, False, False, False, False),
    (11, 8): (-6, 0, None, False, False, False, False),
    (11, 9): (-1, 0, None, False, False, False, False),
    (11, 10): (-2, 0, None, False, False, False, False),
    (11, 11): (0, 0, None, False, False, False, False),
    (11, 12): (0, 0, None, False, False, False, False),


    (12, 1): (-3, 0, None, False, False, False, False),
    (12, 2): (-2, 0, None, False, False, False, False),
    (12, 3): (-3, 0, None, False, False, False, False),
    (12, 4): (-5, 0, None, False, False, False, False),
    (12, 5): (-4, 0, None, False, False, False, False),
    (12, 6): (-5, 0, None, False, False, False, False),
    (12, 7): (0, 0, None, False, False, False, False),
    (12, 8): (-6, 0, None, False, False, False, False),
    (12, 9): (-1, 0, None, False, False, False, False),
    (12, 10): (-2, 0, None, False, False, False, False),
    (12, 11): (0, 0, None, False, False, False, False),
    (12, 12): (0, 0, None, False, False, False, False),
}