
WEARON_P1_ATTACKS = {
    (1, 1): (-3, -8, None, False, False, False, False),
    (1, 2): (-2, -8, None, False, False, False, False),
    (1, 3): (0, -10, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (1, 4): (0, 0, "Кунай выбивается из руки", True, False, False, False),
    (1, 5): (-4, 0, "Нога длиннее руки и достигает цели раньше", False, False, False, False),
    (1, 6): (0, -10, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (1, 7): (0, -2, "Кунай ранит блокирующего", False, False, False, False),
    (1, 8): (0, 0, "Кунай выбивается из руки", True, False, False, False),
    (1, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (1, 10): (-2, 0, "Происходит обезоруживание, кунай выпадает", True, False, False, False),
    (1, 11): (0, -8, None, False, False, False, False),
    (1, 12): (0, -8, None, False, False, False, False),

    (2, 1): (-3, -7, None, False, False, False, False),
    (2, 2): (-2, -7, None, False, False, False, False),
    (2, 3): (-3, 0, "Удар по корпусу не достигает цели", False, False, False, False),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, -2, "Ранит кунаем ногу", False, False, False, False),
    (2, 6): (-5, 0, None, False, False, False, False),
    (2, 7): (0, -3, "Кунай ранит блокирующего", False, False, False, False),
    (2, 8): (0, -7, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, False, False),
    (2, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (2, 10): (-2, 0, "Происходит обезоруживание, кунай выпадает", True, False, False, False),
    (2, 11): (0, -7, None, False, False, False, False),
    (2, 12): (0, -7, None, False, False, False, False),

    (3, 1): (-3, -2, "Кунай ранит руку", False, False, False, False),
    (3, 2): (0, -8, None, False, False, False, False),
    (3, 3): (-3, -8, None, False, False, False, False),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -8, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, -2, "Кунай ранит ногу", False, False, False, False),
    (3, 7): (0, -3, "Кунай ранит блокирующего", False, False, False, False),
    (3, 8): (-6, 0, "Подпрынувший просто отлетает от удара ногой с разворота", False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (0, -8, "Подпрыгнувший пробивается ударом через захват и его нельзя бросить", False, False, False, False),
    (3, 11): (0, -8, None, False, False, False, False),
    (3, 12): (0, -8, None, False, False, False, False),


    (4, 1): (0, -5, None, False, False, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, None, False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (0, -2, "Происходит бросок за ногу, кунай теряется", True, False, False, False),
    (4, 11): (0, -5, None, False, False, False, False),
    (4, 12): (0, -5, None, False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (0, -4, None, False, False, False, False),
    (5, 3): (-3, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-2, 0, "Нога захватывается и производится бросок", False, False, False, False),
    (5, 11): (0, -4, None, False, False, False, False),
    (5, 12): (0, -4, None, False, False, False, False),


    (6, 1): (-3, 0, None, False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (0, -5, None, False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (0, -6, None, False, False, False, False),
    (6, 11): (0, -6, None, False, False, False, False),
    (6, 12): (0, -6, None, False, False, False, False),


    (7, 1): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 2): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 3): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 4): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 5): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 6): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника, кунай выпадает из руки", True, False, False, False),
    (7, 10): (-2, 0, "Происходит захват за блок и бросок, кунай выпадает", True, False, False, False),
    (7, 11): (0, 0, None, False, False, False, False),
    (7, 12): (0, 0, None, False, False, False, False),

    (8, 1): (0, -6, None, False, False, False, False),
    (8, 2): (-2, 0, None, False, False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника, кунай первого игрока теряется", True, False, False, False),
    (8, 10): (0, -6, "Не удается перехватить разворачивающегося противника, происходит удар, бросок не получается", False, False, False, False),
    (8, 11): (0, -6, "Из-за сильного удара кунай выпадает", True, False, False, False),
    (8, 12): (0, -6, "Из-за сильного удара сюрикен выпадает", True, False, False, False),

    (9, 1): (0, -1, None, False, False, False, False),
    (9, 2): (0, -1, None, False, False, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, None, False, False, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Не получается захватить того, кто делает подсечку", False, False, False, False),
    (9, 11): (0, -1, "Противник падает и кунай выпадает из руки", True, False, False, False),
    (9, 12): (0, -1, "Противник падает и сюрикен выпадает из руки", True, False, False, False),

    (10, 1): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 2): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 3): (0, -8, "Происходит метание куная, кунай попадает в корпус и сбивает подпрыгнувшего", True, False, False, False),
    (10, 4): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 5): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 6): (0, -8, "Происходит метание куная, кунай попадает в корпус и сбивает подпрыгнувшего", True, False, False, False),
    (10, 7): (0, -5, "Происходит метание куная, кунай пробивает защиту и попадает в корпус", True, False, False, False),
    (10, 8): (-6, 0, "Благодаря повороту корпуса соперник уклоняется от куная, кунай теряется", True, False, False, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от куная, кунай теряется", True, False, False, False),
    (10, 10): (0, 0, "Противник перехватывает кунай в воздухе и отбрасывает его в сторону, кунай теряется", True, False, False, False),
    (10, 11): (0, -8, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 12): (0, -8, "Происходит метание куная, кунай попадает в голову", True, False, False, False),


    (11, 1): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 2): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 3): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 4): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 5): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 6): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 7): (0, -2, "Игрок наносит серию ударов кунаем, противник с трудом отбивается", False, False, False, False),
    (11, 8): (-6, 0, "Удар сбивает серию ударов игрока, кунай первого игрока теряется", True, False, False, False),
    (11, 9): (0, -5, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", True, False, False, False),
    (11, 10): (-2, -3, "Кунай перехватывается противником после пары ударов серии и теряется", True, False, False, False),
    (11, 11): (0, -7, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (11, 12): (0, -7, "Происходит метание куная, кунай попадает в голову", True, False, False, False),


    (12, 1): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 2): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 3): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 4): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 5): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 6): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 7): (0, 0, None, False, False, False, False),
    (12, 8): (-6, 0, "Достает сюрикен", False, False, False, False),
    (12, 9): (-1, 0, "От подсечки сюрикен выпадает", False, False, False, False),
    (12, 10): (-2, 0, "Игрок отвлекается, противнику удается отобрать и выкинуть кунай", True, False, False, False),
    (12, 11): (0, 0, None, False, False, False, False),
    (12, 12): (0, 0, None, False, False, False, False),}

WEARON_P2_ATTACKS ={
    (1, 1): (-8, -3, None, False, False, False, False),
    (1, 2): (-7, -3, None, False, False, False, False),
    (1, 3): (-2, -3, "Кунай ранит руку", False, False, False, False),
    (1, 4): (-5, 0, None, False, False, False, False),
    (1, 5): (-4, 0, "Нога длиннее руки и достигает цели раньше", False, False, False, False),
    (1, 6): (0, -3, None, False, False, False, False),
    (1, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (1, 8): (-6, 0, None, False, False, False, False),
    (1, 9): (-1, 0, None, False, False, False, False),
    (1, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (1, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (1, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (2, 1): (-8, -2, None, False, False, False, False),
    (2, 2): (-7, -2, None, False, False, False, False),
    (2, 3): (-8, 0, "Удар по корпусу не достигает цели", False, False, False, False),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, 0, "Ранит кунаем ногу", False, False, False, False),
    (2, 6): (-5, 0, None, False, False, False, False),
    (2, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (2, 8): (0, -2, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, False, False),
    (2, 9): (-1, 0, "Первый игрок падает, кунай выпадает", False, False, False, False),
    (2, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (2, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (2, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (3, 1): (-10, 0, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (3, 2): (0, -3, None, False, False, False, False),
    (3, 3): (-8, -3, None, False, False, False, False),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -3, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, 0, None, False, False, False, False),
    (3, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (3, 8): (-6, 0, "Подпрынувший просто отлетает от удара ногой с разворота", False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (-8, 0, "Происходит метание куная, кунай попадает в корпус", False, True, False, False),
    (3, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (3, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (4, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (4, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (4, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (-2, -4, "Ранит кунаем ногу", False, False, False, False),
    (5, 3): (-8, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (5, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (5, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (6, 1): (-10, 0, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (-2, -5, "Кунай ранит ногу", False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-8, 0, "Происходит метание куная, кунай попадает в корпус", False, True, False, False),
    (6, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (6, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (7, 1): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 2): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 3): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 4): (0, 0, "Блок", False, False, False, False),
    (7, 5): (0, 0, "Блок", False, False, False, False),
    (7, 6): (0, 0, "Блок", False, False, False, False),
    (7, 7): (0, 0, "Блок", False, False, False, False),
    (7, 8): (0, 0, "Блок", False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника", False, False, False, False),
    (7, 10): (-5, 0, "Происходит метание куная, кунай пробивает защиту и попадает в корпус", False, True, False, False),
    (7, 11): (-2, 0, "Игрок наносит серию ударов кунаем, противник с трудом отбивается", False, False, False, False),
    (7, 12): (0, 0, None, False, False, False, False),

    (8, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (8, 2): (-7, 0, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (0, -6, "Благодаря повороту корпуса соперник уклоняется от куная, кунай теряется", False, True, False, False),
    (8, 11): (0, -6, "Удар сбивает серию ударов игрока, кунай первого игрока теряется", False, True, False, False),
    (8, 12): (0, -6, "Достает сюрикен", False, False, False, False),

    (9, 1): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 2): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Промахивается броском куная", False, True, False, False),
    (9, 11): (-5, 0, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", False, True, False, False),
    (9, 12): (0, -1, "Противник падает и сюрикен выпадает из руки", False, False, False, False),

    (10, 1): (0, -2, "Происходит обезоруживание, кунай выпадает", False, True, False, False),
    (10, 2): (0, -2, "Происходит обезоруживание, кунай выпадает", False, True, False, False),
    (10, 3): (-5, 0, "Пробивается сквозь бросок и ранит", False, False, False, False),
    (10, 4): (0, -2, "Бросок", False, True, False, False),
    (10, 5): (0, -2, "Бросок", False, True, False, False),
    (10, 6): (-6, 0, "Не удается перехватить подпрыгнувшего", False, False, False, False),
    (10, 7): (0, -2, "Происходит захват за блок и бросок, кунай выпадает", False, True, False, False),
    (10, 8): (-6, 0, "Не удается перехватить разворачивающегося противника, происходит удар, бросок не получается", False, False, False, False),
    (10, 9): (-1, 0, "Подсечка", False, False, False, False),
    (10, 10): (0, 0, "Противник перехватывает кунай в воздухе и отбрасывает его в сторону, кунай теряется", False, True, False, False),
    (10, 11): (-3, -2, "Кунай перехватывается противником после пары ударов серии и теряется", False, True, False, False),
    (10, 12): (-2, 0, "Игрок отвлекается, противнику удается отобрать и выкинуть кунай", False, True, False, False),


    (11, 1): (-8, 0, None, False, False, False, False),
    (11, 2): (-7, 0, None, False, False, False, False),
    (11, 3): (-8, 0, None, False, False, False, False),
    (11, 4): (-5, 0, None, False, False, False, False),
    (11, 5): (-4, 0, None, False, False, False, False),
    (11, 6): (-5, 0, None, False, False, False, False),
    (11, 7): (0, 0, None, False, False, False, False),
    (11, 8): (-6, 0, None, False, False, False, False),
    (11, 9): (-1, 0, "Подсечка", False, False, False, False),
    (11, 10): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 11): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 12): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),


    (12, 1): (-8, 0, None, False, False, False, False),
    (12, 2): (-7, 0, None, False, False, False, False),
    (12, 3): (-8, 0, None, False, False, False, False),
    (12, 4): (-5, 0, None, False, False, False, False),
    (12, 5): (-4, 0, None, False, False, False, False),
    (12, 6): (-5, 0, None, False, False, False, False),
    (12, 7): (0, 0, None, False, False, False, False),
    (12, 8): (-6, 0, None, False, False, False, False),
    (12, 9): (-1, 0, "Подсечка", False, False, False, False),
    (12, 10): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (12, 11): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (12, 12): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),}

WEARON_EFFECTS_DUAL_KUNAI = {
    (1, 1): (-8, -8, None, False, False, False, False),
    (1, 2): (-7, -8, None, False, False, False, False),
    (1, 3): (0, -10, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (1, 4): (0, 0, "Кунай выбивается из руки", True, False, False, False),
    (1, 5): (-4, 0, "Нога длиннее руки и достигает цели раньше", False, False, False, False),
    (1, 6): (0, -10, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (1, 7): (0, 0, "Парирование кунаем", False, False, False, False),
    (1, 8): (0, 0, "Кунай выбивается из руки", True, False, False, False),
    (1, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (1, 10): (0, 0, "Второй игрок бросает кунай, первый игрок отбивает его, кунай второго игрока теряется", False, True, False, False),
    (1, 11): (-5, 0, "Второй игрок наносит серию ударов кунаем, но первый игрок отбивает один из ударов", False, False, False, False),
    (1, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (2, 1): (-8, -7, None, False, False, False, False),
    (2, 2): (-7, -7, None, False, False, False, False),
    (2, 3): (-8, 0, "Удар по корпусу не достигает цели", False, False, False, False),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, -2, "Ранит кунаем ногу", False, False, False, False),
    (2, 6): (-5, 0, None, False, False, False, False),
    (2, 7): (0, 0, "Парирование кунаем", False, False, False, False),
    (2, 8): (0, -7, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, False, False),
    (2, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (2, 10): (-10, 0, "Второй игрок бросает кунай, и попадает в голову, атака первого игрока сбивается, кунай второго игрока теряется", False, True, False, False),
    (2, 11): (-5, 0, "Второй игрок наносит серию ударов кунаем, но первый игрок отбивает один из ударов", False, False, False, False),
    (2, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (3, 1): (-10, 0, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (3, 2): (0, -8, None, False, False, False, False),
    (3, 3): (-8, -8, None, False, False, False, False),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -8, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, -2, "Кунай ранит ногу", False, False, False, False),
    (3, 7): (0, 0, "Парирование кунаем", False, False, False, False),
    (3, 8): (-6, 0, "Подпрынувший просто отлетает от удара ногой с разворота", False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (0, 0, "Второй игрок бросает кунай, первый игрок отбивает его, кунай второго игрока теряется", False, True, False, False),
    (3, 11): (-5, 0, "Второй игрок наносит серию ударов кунаем, но первый игрок отбивает один из ударов", False, False, False, False),
    (3, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (4, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (-2, 0, "Ранит кунаем ногу", False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели, кунай первого игрока выпадает", True, False, False, False),
    (4, 10): (-10, 0, "Второй игрок бросает кунай, и попадает в голову, атака первого игрока сбивается, кунай второго игрока теряется", False, True, False, False),
    (4, 11): (-8, 0, "Второй игрок наносит серию ударов кунаем, и сбивает атаку", False, False, False, False),
    (4, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (-2, -4, "Ранит кунаем ногу", False, False, False, False),
    (5, 3): (-8, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (-2, 0, "Ранит кунаем ногу", False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар, кунай первого игрока теряется", True, False, False, False),
    (5, 10): (-10, 0, "Второй игрок бросает кунай, и попадает в голову, атака первого игрока сбивается, кунай второго игрока теряется", False, True, False, False),
    (5, 11): (-8, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (5, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (6, 1): (-10, 0, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (-2, -5, "Кунай ранит ногу", False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (-2, 0, "Кунай ранит ногу", False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-10, 0, "Второй игрок бросает кунай и попадает в корпус, кунай второго игрока теряется", False, True, False, False),
    (6, 11): (-8, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (6, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),


    (7, 1): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 2): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 3): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 4): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 5): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 6): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, 0, "Парирует удар кунаем", False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника, кунай выпадает из руки", True, False, False, False),
    (7, 10): (0, 0, "Происходит метание куная, первый игрок отбивает кунай, кунай второго игрока теряется", False, True, False, False),
    (7, 11): (0, 0, "Второй игрок наносит серию ударов кунаем, первый игрок успешно блокирует все удары", False, False, False, False),
    (7, 12): (0, 0, "Второй игрок выхватывает сюрикен", False, False, False, False),

    (8, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (8, 2): (-7, 0, None, False, False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (-2, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника, кунай первого игрока теряется", True, False, False, False),
    (8, 10): (0, -6, "Втрой игрок кидает кунай, но из-за разворота не попадает, кунай второго игрока теряется", False, True, False, False),
    (8, 11): (0, -6, "Удар сбивает серию ударов второго игрока, кунай второго игрока теряется", False, True, False, False),
    (8, 12): (0, -6, "Из-за сильного удара сюрикен выпадает", False, False, False, False),

    (9, 1): (0, -1, "Кунай второго противника выпадает из руки", False, True, False, False),
    (9, 2): (0, -1, "Кунай второго противника выпадает из руки", False, True, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, "Подсечка сбивает блокирующего противника, кунай выпадает из руки", False, True, False, False),
    (9, 8): (0, -1, "Подсечка сбивает разворачивающегося противника, кунай второго игрока теряется", False, True, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Второй игрок метает кунай и промахивается, кунай второго игрока теряется", False, True, False, False),
    (9, 11): (-5, 0, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", False, True, False, False),
    (9, 12): (0, -1, "Противник падает и сюрикен выпадает из руки", False, False, False, False),

    (10, 1): (0, 0, "Первый игрок бросает кунай, второй игрок отбивает его, кунай первого игрока теряется", True, False, False, False),
    (10, 2): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 3): (0, 0, "Первый игрок бросает кунай, второй игрок отбивает его, кунай первого игрока теряется", True, False, False, False),
    (10, 4): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 5): (0, -10, "Происходит метание куная, кунай попадает в голову", True, False, False, False),
    (10, 6): (0, -8, "Происходит метание куная, кунай попадает в корпус и сбивает подпрыгнувшего", True, False, False, False),
    (10, 7): (0, 0, "Происходит метание куная, второй игрок отбивает кунай, кунай первого игрока теряется", True, False, False, False),
    (10, 8): (-6, 0, "Благодаря повороту корпуса соперник уклоняется от куная, кунай теряется", True, False, False, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от куная, кунай теряется", True, False, False, False),
    (10, 10): (0, 0, "Кунаи сталкиваются в воздухе и оба теряются", True, True, False, False),
    (10, 11): (0, 0, "Происходит метание куная, второй игрок отбивает кунай, кунай первого игрока теряется", True, False, False, False),
    (10, 12): (0, -7, "Происходит метание куная, кунай попадает в голову", True, False, False, False),


    (11, 1): (0, -5, "Первый игрок наносит серию ударов кунаем, но второй игрок отбивает один из ударов", False, False, False, False),
    (11, 2): (0, -5, "Первый игрок наносит серию ударов кунаем, но второй игрок отбивает один из ударов", False, False, False, False),
    (11, 3): (0, -5, "Первый игрок наносит серию ударов кунаем, но второй игрок отбивает один из ударов", False, False, False, False),
    (11, 4): (0, -8, "Первый игрок наносит серию ударов кунаем, и сбивает атаку", False, False, False, False),
    (11, 5): (0, -8, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 6): (0, -5, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False, False),
    (11, 7): (0, 0, "Игрок наносит серию ударов кунаем, противник успешно блокирует все удары", False, False, False, False),
    (11, 8): (-6, 0, "Удар сбивает серию ударов второго игрока, кунай первого игрока теряется", True, False, False, False),
    (11, 9): (0, -5, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", True, False, False, False),
    (11, 10): (0, 0, "Происходит метание куная, первый игрок отбивает кунай, кунай второго игрока теряется", False, True, False, False),
    (11, 11): (0, 0, "Происходит взаимный обмен ударами, все удары блокируются", False, False, False, False),
    (11, 12): (0, -7, "Происходит метание куная, кунай попадает в голову", True, False, False, False),


    (12, 1): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 2): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 3): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 4): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 5): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 6): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),
    (12, 7): (0, 0, None, False, False, False, False),
    (12, 8): (-6, 0, "От сильного удара сюрикен выпадает", False, False, False, False),
    (12, 9): (-1, 0, "От подсечки сюрикен выпадает", False, False, False, False),
    (12, 10): (-10, 0, "Игрок отвлекается, противнику удается метнуть кунай в голову, кунай второго игрока теряется", False, True, False, False),
    (12, 11): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (12, 12): (0, 0, "Оба игрока достают еще и сюрикены", False, False, False, False),
}