
SHURIKEN_P1_ATTACKS = {
    (1, 1): (0, -8, None, False, False, True, False),
    (1, 2): (0, -8, None, False, False, True, False),
    (1, 3): (0, -10, "Подпрыгнувший сбивается сюрикеном", False, False, True, False),
    (1, 4): (0, -8, None, False, False, True, False),
    (1, 5): (0, -8, None, False, False, True, False),
    (1, 6): (0, -10, "Подпрыгнувший сбивается сюрикеном", False, False, True, False),
    (1, 7): (0, -3, "Сюрикен ранит блокирующего", False, False, True, False),
    (1, 8): (0, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (1, 9): (-1, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (1, 10): (0, 0, "Второй игрок сбивает сюрикен", False, False, True, False),
    (1, 11): (0, -8, None, False, False, True, False),
    (1, 12): (0, -8, None, False, False, True, False),

    (2, 1): (0, -7, None, False, False, True, False),
    (2, 2): (0, -7, None, False, False, True, False),
    (2, 3): (-3, 0, "Второй игрок перепрыгивает сюрикен и наносит удар", False, False, True, False),
    (2, 4): (0, -7, None, False, False, True, False),
    (2, 5): (0, -7, "Сюрикен сбивает атаку", False, False, True, False),
    (2, 6): (-5, 0, "Второй игрок перепрыгивает сюрикен и наносит удар", False, False, True, False),
    (2, 7): (0, -3, "Сюрикен ранит блокирующего", False, False, True, False),
    (2, 8): (0, -7, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, True, False),
    (2, 9): (-1, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (2, 10): (0, 0, "Второй игрок сбивает сюрикен", False, False, True, False),
    (2, 11): (0, -7, None, False, False, True, False),
    (2, 12): (0, -7, None, False, False, True, False),

    (3, 1): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 2): (0, -10, None, False, False, True, False),
    (3, 3): (0, -10, None, False, False, True, False),
    (3, 4): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 5): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 6): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 7): (0, -5, "Сюрикен ранит блокирующего", False, False, True, False),
    (3, 8): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, True, False),
    (3, 10): (0, -5, "Противник пытается сбить сюрикен, но ему пронзает руку", False, False, True, False),
    (3, 11): (0, -10, None, False, False, True, False),
    (3, 12): (0, -10, None, False, False, True, False),


    (4, 1): (0, -5, None, False, False, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, None, False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (0, -2, "Происходит бросок за ногу", False, False, False, False),
    (4, 11): (0, -5, None, False, False, False, False),
    (4, 12): (0, -5, None, False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (0, -4, None, False, False, False, False),
    (5, 3): (-3, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-2, 0, "Нога захватывается и производится бросок", False, False, False, False),
    (5, 11): (0, -4, None, False, False, False, False),
    (5, 12): (0, -4, None, False, False, False, False),


    (6, 1): (-3, 0, None, False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (0, -5, None, False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (0, -6, None, False, False, False, False),
    (6, 11): (0, -6, None, False, False, False, False),
    (6, 12): (0, -6, None, False, False, False, False),


    (7, 1): (0, 0, None, False, False, False, False),
    (7, 2): (0, 0, None, False, False, False, False),
    (7, 3): (0, 0, None, False, False, False, False),
    (7, 4): (0, 0, None, False, False, False, False),
    (7, 5): (0, 0, None, False, False, False, False),
    (7, 6): (0, 0, None, False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, 0, None, False, False, False, False),
    (7, 9): (-1, 0, None, False, False, False, False),
    (7, 10): (-2, 0, None, False, False, False, False),
    (7, 11): (0, 0, None, False, False, False, False),
    (7, 12): (0, 0, None, False, False, False, False),

    (8, 1): (0, -6, None, False, False, False, False),
    (8, 2): (-2, 0, None, False, False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (0, -6, "Не удается перехватить разворачивающегося противника, происходит удар, бросок не получается", False, False, False, False),
    (8, 11): (0, -6, "Из-за сильного удара кунай выпадает", False, False, False, False),
    (8, 12): (0, -6, "Из-за сильного удара сюрикен выпадает", False, False, False, False),

    (9, 1): (0, -1, None, False, False, False, False),
    (9, 2): (0, -1, None, False, False, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, None, False, False, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Не получается захватить того, кто делает подсечку", False, False, False, False),
    (9, 11): (0, -1, "Противник падает", False, False, False, False),
    (9, 12): (0, -1, "Противник падает", False, False, False, False),

    (10, 1): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 3): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (10, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (10, 7): (0, -5, "Происходит метание, сюрикен пробивает защиту и попадает в корпус", False, False, True, False),
    (10, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (10, 10): (0, 0, "Противник сбивает сюрикен в воздухе", False, False, True, False),
    (10, 11): (0, -10, "Происходит метание сюрикена, сюрикен попадает в голову", False, False, True, False),
    (10, 12): (0, -10, "Происходит метание сюрикена, сюрикен попадает в голову", False, False, True, False),


    (11, 1): (-3, 0, "Игрок достает кунай", False, False, False, False),
    (11, 2): (-2, 0, "Игрок достает кунай", False, False, False, False),
    (11, 3): (-3, 0, "Игрок достает кунай", False, False, False, False),
    (11, 4): (-5, 0, "Игрок достает кунай", False, False, False, False),
    (11, 5): (-4, 0, "Игрок достает кунай", False, False, False, False),
    (11, 6): (-5, 0, "Игрок достает кунай", False, False, False, False),
    (11, 7): (0, 0, "Игрок достает кунай", False, False, False, False),
    (11, 8): (-6, 0, "Игрок достает кунай", False, False, False, False),
    (11, 9): (-1, 0, "Игрок достает кунай", False, False, False, False),
    (11, 10): (-2, 0, "Игрок достает кунай", False, False, False, False),
    (11, 11): (0, 0, "Оба игрока достают кунай", False, False, False, False),
    (11, 12): (0, 0, "Первый игрок достает еще и кунай", False, False, False, False),


    (12, 1): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 3): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (12, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (12, 7): (0, -5, "Происходит метание, сюрикен пробивает защиту и попадает в корпус", False, False, True, False),
    (12, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (12, 10): (0, 0, "Противник сбивает сюрикен в воздухе", False, False, True, False),
    (12, 11): (0, -10, "Второй игрок достает кунай, первый игрок метае сюрикен", False, False, True, False),
    (12, 12): (0, -10, "Метает сюрикен, второй игрок достает сюрикен", False, False, True, False)}

SHURIKEN_P2_ATTACKS = {
    (1, 1): (-8, 0, None, False, False, False, True),
    (1, 2): (-8, 0, None, False, False, False, True),
    (1, 3): (-10, 0, None, False, False, False, True),
    (1, 4): (-5, 0, None, False, False, False, False),
    (1, 5): (-4, 0, None, False, False, False, False),
    (1, 6): (0, -3, None, False, False, False, False),
    (1, 7): (0, 0, None, False, False, False, False),
    (1, 8): (-6, 0, None, False, False, False, False),
    (1, 9): (-1, 0, None, False, False, False, False),
    (1, 10): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (1, 11): (0, -3, "Второй игрок достаёт кунай", False, False, False, False),
    (1, 12): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),

    (2, 1): (-8, 0, None, False, False, False, True),
    (2, 2): (-8, 0, None, False, False, False, True),
    (2, 3): (-10, 0, "Первый игрок перепрыгивает сюрикен и наносит удар", False, False, False, True),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, 0, None, False, False, False, False),
    (2, 6): (-5, 0, None, False, False, False, False),
    (2, 7): (0, 0, None, False, False, False, False),
    (2, 8): (-6, 0, None, False, False, False, False),
    (2, 9): (-1, 0, None, False, False, False, False),
    (2, 10): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (2, 11): (0, -2, "Второй игрок достаёт кунай", False, False, False, False),
    (2, 12): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),

    (3, 1): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (3, 2): (0, -3, "Первый игрок перепрыгивает сюрикен", False, False, False, True),
    (3, 3): (-10, 0, None, False, False, False, True),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -3, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, 0, None, False, False, False, False),
    (3, 7): (0, 0, None, False, False, False, False),
    (3, 8): (-6, 0, None, False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),
    (3, 11): (0, -3, "Второй игрок достаёт кунай", False, False, False, False),
    (3, 12): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),


    (4, 1): (-8, 0, None, False, False, False, True),
    (4, 2): (-7, 0, None, False, False, False, True),
    (4, 3): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (0, -4, "Удар ногой в корпус сбивает второго игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, None, False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-8, 0, None, False, False, False, True),
    (4, 11): (-5, 0, "Второй игрок достаёт кунай", False, False, False, False),
    (4, 12): (-8, 0, None, False, False, False, True),

    (5, 1): (-8, 0, None, False, False, False, True),
    (5, 2): (-7, 0, None, False, False, False, True),
    (5, 3): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-8, 0, None, False, False, False, True),
    (5, 11): (0, -4, "Второй игрок достаёт кунай", False, False, False, False),
    (5, 12): (-8, 0, None, False, False, False, True),


    (6, 1): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (6, 2): (0, -5, "Первый игрок перепрыгивает сюрикен", False, False, False, True),
    (6, 3): (-10, 0, None, False, False, False, True),
    (6, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),
    (6, 11): (0, -5, "Второй игрок достаёт кунай", False, False, False, False),
    (6, 12): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),


    (7, 1): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, False),
    (7, 2): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, False),
    (7, 3): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, False),
    (7, 4): (0, 0, None, False, False, False, False),
    (7, 5): (0, 0, None, False, False, False, False),
    (7, 6): (0, 0, None, False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, 0, None, False, False, False, False),
    (7, 9): (-1, 0, None, False, False, False, False),
    (7, 10): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, False),
    (7, 11): (0, 0, "Достает кунай", False, False, False, False),
    (7, 12): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, False),

    (8, 1): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),
    (8, 2): (-7, 0, None, False, False, False, True),
    (8, 3): (-10, 0, None, False, False, False, True),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),
    (8, 11): (0, -6, "Достает кунай", False, False, False, False),
    (8, 12): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),

    (9, 1): (0, -1, "Уклоняется от сюрикена", False, False, False, True),
    (9, 2): (0, -1, "Уклоняется от сюрикена", False, False, False, True),
    (9, 3): (0, 0, "Уклоняется от сюрикена", False, False, False, True),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, None, False, False, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Уклоняется от сюрикена", False, False, False, True),
    (9, 11): (0, -1, "Противник в падении достает кунай", False, False, False, False),
    (9, 12): (0, -1, "Уклоняется от сюрикена", False, False, False, True),

    (10, 1): (-10, 0, "Происходит метание сюрикена в голову", False, False, False, True),
    (10, 2): (-10, 0, "Происходит метание сюрикена в голову", False, False, False, True),
    (10, 3): (-10, 0, "Происходит метание сюрикена в голову", False, False, False, True),
    (10, 4): (-2, 0, "Бросок", False, False, False, False),
    (10, 5): (-2, 0, "Бросок", False, False, False, False),
    (10, 6): (-6, 0, "Не удается перехватить подпрыгнувшего", False, False, False, False),
    (10, 7): (0, -2, "Происходит захват за блок и бросок, кунай выпадает", False, False, False, False),
    (10, 8): (-6, 0, "Не удается перехватить разворачивающегося противника, происходит удар, бросок не получается", False, False, False, False),
    (10, 9): (-1, 0, "Подсечка", False, False, False, False),
    (10, 10): (0, 0, "Противник сбивает сюрикен в воздухе", False, False, False, False),
    (10, 11): (0, -2, "ОТнимает сюрикен, но противник достает кунай", False, False, False, True),
    (10, 12): (0, 0, "Противник сбивает сюрикен в воздухе", False, False, False, False),


    (11, 1): (-10, 0, None, False, False, False, True),
    (11, 2): (-10, 0, None, False, False, False, True),
    (11, 3): (-10, 0, None, False, False, False, True),
    (11, 4): (-5, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 5): (-4, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 6): (-5, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 7): (0, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 8): (-6, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 9): (-1, 0, "Игрок достает кунай", None, False, False, False, False),
    (11, 10): (-8, 0, None, False, False, False, True),
    (11, 11): (0, 0, "Оба игрока достают кунай", None, False, False, False, False),
    (11, 12): (-8, 0, None, False, False, False, True),


    (12, 1): (-10, 0, None, False, False, False, True),
    (12, 2): (-10, 0, None, False, False, False, True),
    (12, 3): (-10, 0, None, False, False, False, True),
    (12, 4): (-5, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 5): (-4, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 6): (-5, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 7): (0, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 8): (-6, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 9): (-1, 0, "Игрок достает сюрикен", None, False, False, False, False),
    (12, 10): (-8, 0, None, False, False, False, True),
    (12, 11): (0, 0, "Достает сюрикен, второй достает кунай", None, False, False, False, False),
    (12, 12): (-8, 0, None, False, False, False, True)}

SHURIKEN_DUAL_ATTACKS = {
    (1, 1): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (1, 2): (-10, -10, None, False, False, True, True),
    (1, 3): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (1, 4): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (1, 5): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (1, 6): (0, -10, "Подпрыгнувший нанизывается на сюрикен", False, False, True, False),
    (1, 7): (0, -3, "Сюрикен ранит блокирующего", False, False, True, False),
    (1, 8): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (1, 9): (-1, 0, "Первый игрок промахивается и падает", True),
    (1, 10): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (1, 11): (0, 0, "Сюрикен отбивается кунаем", False, False, True, False),
    (1, 12): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),

    (2, 1): (-10, -10, None, False, False, True, True),
    (2, 2): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (2, 3): (-10, 0, "Сюрикен второго игрока сильно вонзается в первого", False, False, True, True),
    (2, 4): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (2, 5): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (2, 6): (-5, 0, None, False, False, True, False),
    (2, 7): (0, -3, "Сюрикен ранит блокирующего", False, False, True, False),
    (2, 8): (0, -10, "Сюрикен сбивает атаку второго игрока", False, False, True, False),
    (2, 9): (-1, 0, "Первый игрок падает", False, False, True, False),
    (2, 10): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (2, 11): (0, 0, "Сюрикен отбивается кунаем", False, False, True, False),
    (2, 12): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),

    (3, 1): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (3, 2): (0, -10, "Сюрикен с инерцией вонзается во второго игрока", False, False, True, True),
    (3, 3): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (3, 4): (0, -10, "Сюрикен с инерцией вонзается во второго игрока", False, False, True, False),
    (3, 5): (0, -10, "Сюрикен с инерцией вонзается во второго игрока", False, False, True, False),
    (3, 6): (0, -10, "Сюрикен с инерцией вонзается во второго игрока", False, False, True, False),
    (3, 7): (0, -3, "Сюрикен ранит блокирующего", False, False, True, False),
    (3, 8): (0, -10, "Сюрикен с инерцией вонзается во второго игрока", False, False, True, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, True, False),
    (3, 10): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (3, 11): (0, 0, "Сюрикен отбивается кунаем", False, False, True, False),
    (3, 12): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),


    (4, 1): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (4, 2): (-10, 0, "Сюрикен попадает в корпус", False, False, False, True),
    (4, 3): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, None, False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-10, 0, "Второй игрок бросает сюрикен, и попадает в голову, атака первого игрока сбивается", False, False, False, True),
    (4, 11): (0, -3, "Второй игрок достает кунай", False, False, False, False),
    (4, 12): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),

    (5, 1): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (5, 2): (-10, 0, "Сюрикен попадает в корпус", False, False, False, True),
    (5, 3): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-10, 0, "Второй игрок бросает сюрикен, и попадает в голову, атака первого игрока сбивается", False, False, False, True),
    (5, 11): (0, -4, "Второй игрок достает кунай", False, False, False, False),
    (5, 12): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),


    (6, 1): (-10, 0, "Подпрыгнувший нанизывается на сюрикен", False, False, False, True),
    (6, 2): (0, -5, None, False, False, False, True),
    (6, 3): (-10, 0, "Сюрикен с инерцией вонзается в первого игрока", False, False, False, True),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-10, 0, "Второй игрок бросает сюрикен и попадает в корпус", False, False, False, True),
    (6, 11): (0, -5, "Игрок достает кунай", False, False, False, False),
    (6, 12): (-10, 0, "Происходит метание сюрикена в корпус", False, False, False, True),


    (7, 1): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, True),
    (7, 2): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, True),
    (7, 3): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, True),
    (7, 4): (0, 0, None, False, False, False, False),
    (7, 5): (0, 0, None, False, False, False, False),
    (7, 6): (0, 0, None, False, False, False, False),
    (7, 7): (0, 0, None, False, False, False, False),
    (7, 8): (0, 0, None, False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника", False, False, False, False),
    (7, 10): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, True),
    (7, 11): (0, 0, "Второй игрок достает кунай", False, False, False, False),
    (7, 12): (-3, 0, "Сюрикен ранит блокирующего", False, False, False, True),

    (8, 1): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (8, 2): (-10, 0, "Сюрикен попадает в корпус", False, False, False, True),
    (8, 3): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (8, 11): (0, -6, "Второй игрок выхватывает кунай", False, False, False, False),
    (8, 12): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),

    (9, 1): (0, -1, "Сюрикен пролетает мимо", False, False, False, True),
    (9, 2): (0, -1, "Сюрикен пролетает мимо", False, False, False, True),
    (9, 3): (0, 0, None, False, False, False, True),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, "Подсечка сбивает блокирующего противника", False, False, False, False),
    (9, 8): (0, -1, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Второй игрок метает сюрикен и промахивается", False, False, False, True),
    (9, 11): (0, -1, "Игрок достает кунай,но падает", False, False, False, False),
    (9, 12): (0, -1, "Второй игрок метает сюрикен и промахивается", False, False, False, True),

    (10, 1): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (10, 2): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (10, 3): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (10, 4): (0, -10, "Происходит метание,сюрикен попадает в голову", False, False, True, False),
    (10, 5): (0, -10, "Происходит метание,сюрикен попадает в голову", False, False, True, False),
    (10, 6): (0, -10, "Происходит метание,сюрикен попадает в корпус", True),
    (10, 7): (0, -3, "Происходит метание, сюрикен ранит блокирующего", False, False, True, False),
    (10, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (10, 10): (0, 0, "Сюрикены сталкиваются в воздухе и оба теряются", False, False, True, True),
    (10, 11): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 12): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),


    (11, 1): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (11, 2): (-8, 0, "Сюрикен попадает в корпус", False, False, False, True),
    (11, 3): (-10, 0, "Сюрикен попадает в голову", False, False, False, True),
    (11, 4): (-5, 0, "Первый игрок достает кунай", False, False, False, False),
    (11, 5): (-4, 0, "Первый игрок достает кунай", False, False, False, False),
    (11, 6): (-5, 0, "Первый игрок достает кунай", False, False, False, False),
    (11, 7): (0, 0, "Первый игрок достает кунай", False, False, False, False),
    (11, 8): (-6, 0, "Удар с разворота", False, False, False, False),
    (11, 9): (-1, 0, "Игрок достает кунай, но падает", False, False, False, False),
    (11, 10): (0, 0, "Сюрикен блокируется кунаем", False, False, False, True),
    (11, 11): (0, 0, "Оба игрока достают кунай", False),
    (11, 12): (0, 0, "Сюрикен блокируется кунаем", False, False, False, True),


    (12, 1): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (12, 2): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (12, 3): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
    (12, 4): (0, -10, "Происходит метание,сюрикен попадает в голову", False, False, True, False),
    (12, 5): (0, -10, "Происходит метание,сюрикен попадает в голову", False, False, True, False),
    (12, 6): (0, -8, "Происходит метание,сюрикен попадает в корпус", False, False, True, False),
    (12, 7): (0, -3, None, False, False, True, False),
    (12, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (12, 10): (0, 0, "Сюрикены сталкиваются в воздухе и оба теряются", False, False, True, True),
    (12, 11): (-0, 0, "Отбивает кунаем", False, False, True, False),
    (12, 12): (0, 0, "Сюрикены сталкиваются в воздухе", False, False, True, True),
}