SHURIKEN_P1_KUNAI_P2_ATTACKS = {
    (1, 1): (0, 0, "Парирует кунаем", False, False, True, False),
    (1, 2): (0, -8, "атака сбивается", False, False, True, False),
    (1, 3): (0, 0, "Парирует кунаем", False, False, True, False),
    (1, 4): (0, -8, None, False, False, True, False),
    (1, 5): (0, -8, None, False, False, True, False),
    (1, 6): (0, -10, "Подпрыгнувший сбивается сюрикеном", False, False, True, False),
    (1, 7): (0, 0, "Парирует кунаем", False, False, True, False),
    (1, 8): (0, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (1, 9): (-1, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (1, 10): (0, 0, "Кунай и сюрикен сталкиваются в воздухе", False, True, True, False),
    (1, 11): (0, 0, "Парирует кунаем", False, False, True, False),
    (1, 12): (0, 0, "Парирует кунаем, одновременно доставая сюрикен", False, False, True, False),

    (2, 1): (0, -7, None, False, False, True, False),
    (2, 2): (0, 0, "Парирует кунаем", False, False, True, False),
    (2, 3): (-8, 0, "Второй игрок перепрыгивает сюрикен и наносит удар", False, False, True, False),
    (2, 4): (0, -7, None, False, False, True, False),
    (2, 5): (0, -7, "Сюрикен сбивает атаку", False, False, True, False),
    (2, 6): (-5, 0, "Второй игрок перепрыгивает сюрикен и наносит удар", False, False, True, False),
    (2, 7): (0, 0, "Парирует кунаем", False, False, True, False),
    (2, 8): (0, -7, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False, False, True, False),
    (2, 9): (-1, 0, "Сюрикен пролетает мимо", False, False, True, False),
    (2, 10): (0, 0, "Кунай и сюрикен сталкиваются в воздухе", False, True, True, False),
    (2, 11): (0, 0, "Парирует кунаем", False, False, True, False),
    (2, 12): (0, 0, "Парирует кунаем, одновременно доставая сюрикен", False, False, True, False),

    (3, 1): (0, 0, "Парирует кунаем", False, False, True, False),
    (3, 2): (0, -10, None, False, False, True, False),
    (3, 3): (0, 0, "Парирует кунаем", False, False, True, False),
    (3, 4): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 5): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 6): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 7): (0, 0, "Парирует кунаем", False, False, True, False),
    (3, 8): (0, -10, "Сюрикен с инерцией вонзается в противника", False, False, True, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, True, False),
    (3, 10): (0, 0, "Кунай и сюрикен сталкиваются в воздухе", False, True, True, False),
    (3, 11): (0, 0, "Парирует кунаем", False, False, True, False),
    (3, 12): (0, 0, "Парирует кунаем, одновременно доставая сюрикен", False, False, True, False),

    (4, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (4, 2): (0, -5, None, False, False, False, False),
    (4, 3): (0, -5, None, False, False, False, False),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (4, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False,
    False),
    (4, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (5, 1): (0, -4, None, False, False, False, False),
    (5, 2): (-2, -4, "Ранит кунаем ногу", False, False, False, False),
    (5, 3): (-8, 0, None, False, False, False, False),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-10, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (5, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False,
    False),
    (5, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (6, 1): (-10, 0, "Подпрыгнувший нанизывается на кунай", False, False, False, False),
    (6, 2): (0, -5, None, False, False, False, False),
    (6, 3): (-2, -5, "Кунай ранит ногу", False, False, False, False),
    (6, 4): (0, -5, None, False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-8, 0, "Происходит метание куная, кунай попадает в корпус", False, True, False, False),
    (6, 11): (-5, 0, "Игрок наносит серию ударов кунаем, наносящую повреждения и сбивающую атаку противника", False, False, False,
    False),
    (6, 12): (0, 0, "Удар блокируется кунаем с одновременным доставанием сюрикена", False, False, False, False),

    (7, 1): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 2): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 3): (-3, 0, "Кунай ранит блокирующего", False, False, False, False),
    (7, 4): (0, 0, "Блок", False, False, False, False),
    (7, 5): (0, 0, "Блок", False, False, False, False),
    (7, 6): (0, 0, "Блок", False, False, False, False),
    (7, 7): (0, 0, "Блок", False, False, False, False),
    (7, 8): (0, 0, "Блок", False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника", False, False, False, False),
    (7, 10): (-5, 0, "Происходит метание куная, кунай пробивает защиту и попадает в корпус", False, True, False, False),
    (7, 11): (-2, 0, "Игрок наносит серию ударов кунаем, противник с трудом отбивается", False, False, False, False),
    (7, 12): (0, 0, None, False, False, False, False),

    (8, 1): (0, 0, "Кунай выбивается из руки", False, True, False, False),
    (8, 2): (-7, 0, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False,
    False, False, False),
    (8, 3): (0, -6, None, False, False, False, False),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (-2, 0, "Парирует удар кунаем", False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника", False, False, False, False),
    (8, 10): (0, -6, "Благодаря повороту корпуса соперник уклоняется от куная, кунай теряется", False, True, False, False),
    (8, 11): (0, -6, "Удар сбивает серию ударов игрока, кунай первого игрока теряется", False, True, False, False),
    (8, 12): (0, -6, "Достает сюрикен", False, False, False, False),

    (9, 1): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 2): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Промахивается броском куная", False, True, False, False),
    (9, 11): (-5, 0, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", False, True, False,
    False),
    (9, 12): (0, -1, "Противник падает", False, False, False, False),

    (10, 1): (0, 0, "Происходит метание сюрикена в голову, парирует кунаем", False, False, True, False),
    (10, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 3): (0, 0, "Происходит метание сюрикена в корпус, парирует кунаем", False, False, True, False),
    (10, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (10, 7): (0, 0, "Происходит метание, парирует кунаем", False, False, True, False),
    (10, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (10, 10): (0, 0, "Противник сбивает сюрикен в воздухе кунаем", False, True, True, False),
    (10, 11): (0, 0, "Происходит метание сюрикена, парирует кунаем", False, False, True, False),
    (10, 12): (0, 0, "Происходит метание сюрикена, парирует кунаем и достает сюрикен", False, False, True, False),

    (11, 1): (-8, 0, None, False, False, False, False),
    (11, 2): (-7, 0, None, False, False, False, False),
    (11, 3): (-8, 0, None, False, False, False, False),
    (11, 4): (-5, 0, None, False, False, False, False),
    (11, 5): (-4, 0, None, False, False, False, False),
    (11, 6): (-5, 0, None, False, False, False, False),
    (11, 7): (0, 0, None, False, False, False, False),
    (11, 8): (-6, 0, None, False, False, False, False),
    (11, 9): (-1, 0, "Подсечка", False, False, False, False),
    (11, 10): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 11): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 12): (0, 0, "Достает кунай, а вторй достает сюрикен", False, False, False, False),


    (12, 1): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 3): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (12, 7): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (12, 10): (0, 0, "Противник сбивает сюрикен в воздухе кунаем", False, True, True, False),
    (12, 11): (0, -10, "Первый игрок метает сюрикен и сбивает атаку кунаем", False, False, True, False),
    (12, 12): (0, -10, "Метает сюрикен, второй игрок достает сюрикен", False, False, True, False)}

SHURIKEN_P2_KUNAI_P1_ATTACKS = {
    (1, 1): (0, 0, "Парирует кунаем", False, False, False, True),
    (1, 2): (-8, 0, "атака сбивается", False, False, False, True),
    (1, 3): (0, 0, "Парирует кунаем", False, False, False, True),
    (1, 4): (0, -8, None, False, False, False, True),
    (1, 5): (0, -8, None, False, False, False, True),
    (1, 6): (0, -10, "Подпрыгнувший сбивается сюрикеном", False, False, False, True),
    (1, 7): (0, -2, "Кунай ранит блокирующего", False, False, False, False),
    (1, 8): (0, 0, "Кунай выбивается из руки", True, False, False, False),
    (1, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (1, 10): (0, 0, "Парирует кунаем", False, False, False, True),
    (1, 11): (0, -8, None, False, False, False, False),
    (1, 12): (0, 0, "Парирует кунаем", False, False, False, True),

    (2, 1): (-8, 0, "атака сбивается", False, False, False, True),
    (2, 2): (0, 0, "Парирует кунаем", False, False, False, True),
    (2, 3): (-10, 0, "Сюрикен с инерцией вонзается", False, False, False, True),
    (2, 4): (-5, 0, None, False, False, False, False),
    (2, 5): (-4, -2, "Ранит кунаем ногу", False, False, False, False),
    (2, 6): (-5, 0, "Второй игрок наносит удар", False, False, False, False),
    (2, 7): (0, -3, "Кунай ранит блокирующего", False, False, False, False),
    (2, 8): (0, -7, "Во время разворота корпус открыт, удар достигает цели и сбивает противника, не давая закончить удар", False,
    False, False, False),
    (2, 9): (-1, 0, "Первый игрок падает, кунай выпадает", True, False, False, False),
    (2, 10): (0, 0, "Парирует кунаем", False, False, False, True),
    (2, 11): (0, -7, "Второй игрок достает кунай", False, False, False, False),
    (2, 12): (0, 0, "Парирует кунаем", False, False, False, True),

    (3, 1): (0, 0, "Парирует кунаем", False, False, False, True),
    (3, 2): (0, -8, None, False, False, False, True),
    (3, 3): (0, 0, "Парирует кунаем", False, False, False, True),
    (3, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (3, 5): (0, -8, "Бьющий ногой промахивается, а вот рука попадает в цель", False, False, False, False),
    (3, 6): (-5, -2, "Кунай ранит ногу", False, False, False, False),
    (3, 7): (0, -3, "Кунай ранит блокирующего", False, False, False, False),
    (3, 8): (-6, 0, "Подпрынувший просто отлетает от удара ногой с разворота", False, False, False, False),
    (3, 9): (0, 0, "Первый противник пролетает над вторым, обмена ударами не состоялось", False, False, False, False),
    (3, 10): (0, 0, "Парирует кунаем", False, False, False, True),
    (3, 11): (0, -8, None, False, False, False, False),
    (3, 12): (0, 0, "Парирует кунаем", False, False, False, True),

    (4, 1): (-8, 0, None, False, False, False, True),
    (4, 2): (-7, 0, None, False, False, False, True),
    (4, 3): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (4, 4): (-3, -3, "Ноги больно сталкиваются в воздухе", False, False, False, False),
    (4, 5): (-4, 0, "Удар ногой в корпус сбивает первого игрока", False, False, False, False),
    (4, 6): (0, -5, None, False, False, False, False),
    (4, 7): (0, 0, "Блок", False, False, False, False),
    (4, 8): (-6, 0, "Удар ногой с разворота срабатывает как контратака", False, False, False, False),
    (4, 9): (-1, 0, "Удар в голову не достигает цели", False, False, False, False),
    (4, 10): (-8, 0, None, False, False, False, True),
    (4, 11): (-5, 0, "Второй игрок достаёт кунай", False, False, False, False),
    (4, 12): (-8, 0, None, False, False, False, True),

    (5, 1): (-8, 0, None, False, False, False, True),
    (5, 2): (-7, 0, None, False, False, False, True),
    (5, 3): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (5, 4): (0, -4, None, False, False, False, False),
    (5, 5): (-4, -4, None, False, False, False, False),
    (5, 6): (-5, 0, None, False, False, False, False),
    (5, 7): (0, 0, None, False, False, False, False),
    (5, 8): (0, -4, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (5, 9): (-1, 0, "Противник падает и не наносит удар", False, False, False, False),
    (5, 10): (-8, 0, None, False, False, False, True),
    (5, 11): (0, -4, "Второй игрок достаёт кунай", False, False, False, False),
    (5, 12): (-8, 0, None, False, False, False, True),

    (6, 1): (-10, 0, "Сюрикен с инерцией вонзается в противника", False, False, False, True),
    (6, 2): (0, -5, "Первый игрок перепрыгивает сюрикен", False, False, False, True),
    (6, 3): (-10, 0, None, False, False, False, True),
    (6, 4): (-5, 0, "Удар ногой отбивает подпрыгнувшего", False, False, False, False),
    (6, 5): (0, -5, None, False, False, False, False),
    (6, 6): (-5, -5, None, False, False, False, False),
    (6, 7): (0, 0, None, False, False, False, False),
    (6, 8): (-6, 0, "Удар ногой с разворота сбивает летящего", False, False, False, False),
    (6, 9): (0, 0, None, False, False, False, False),
    (6, 10): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),
    (6, 11): (0, -5, "Второй игрок достаёт кунай", False, False, False, False),
    (6, 12): (-8, 0, "Происходит метание сюрикена,он попадает в корпус", False, False, False, True),

    (7, 1): (0, 0, "Кунай блокирует сюрикен", False, False, False, True),
    (7, 2): (0, 0, "Кунай блокирует сюрикен", False, False, False, True),
    (7, 3): (0, 0, "Кунай блокирует сюрикен", False, False, False, True),
    (7, 4): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 5): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 6): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 7): (0, 0, "Блок", False, False, False, False),
    (7, 8): (0, -2, "Парирует удар кунаем", False, False, False, False),
    (7, 9): (-1, 0, "Подсечка сбивает блокирующего противника, кунай выпадает из руки", True, False, False, False),
    (7, 10): (0, 0, "Кунай блокирует сюрикен", False, False, False, True),
    (7, 11): (0, 0, None, False, False, False, False),
    (7, 12): (0, 0, "Кунай блокирует сюрикен", False, False, False, True),

    (8, 1): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),
    (8, 2): (-7, 0, None, False, False, False, True),
    (8, 3): (-10, 0, None, False, False, False, True),
    (8, 4): (0, -6, None, False, False, False, False),
    (8, 5): (-4, 0, "Удар ногой сбивает разворачивающегося противника", False, False, False, False),
    (8, 6): (0, -6, None, False, False, False, False),
    (8, 7): (0, 0, None, False, False, False, False),
    (8, 8): (-6, -6, None, False, False, False, False),
    (8, 9): (-1, 0, "Подсечка сбивает разворачивающегося противника, кунай первого игрока теряется", True, False, False, False),
    (8, 10): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),
    (8, 11): (0, -6, "Достает кунай", False, False, False, False),
    (8, 12): (0, 0, "Разворот позволяет уклониться от сюрикена", False, False, False, True),

    (9, 1): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 2): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 3): (0, 0, None, False, False, False, False),
    (9, 4): (0, -1, None, False, False, False, False),
    (9, 5): (0, -1, None, False, False, False, False),
    (9, 6): (0, 0, None, False, False, False, False),
    (9, 7): (0, -1, "Второй игрок падает, кунай выпадает", False, True, False, False),
    (9, 8): (0, -1, None, False, False, False, False),
    (9, 9): (-1, -1, None, False, False, False, False),
    (9, 10): (0, -1, "Промахивается броском куная", False, True, False, False),
    (9, 11): (
    -5, 0, "Игрок совершает бросок куная по нижнему уровню и сбивает подсечку, кунай теряется", False, True, False,
    False),
    (9, 12): (0, -1, "Противник падает", False, False, False, False),

    (10, 1): (0, 0, "Происходит метание сюрикена в голову, парирует кунаем", False, False, True, False),
    (10, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 3): (0, 0, "Происходит метание сюрикена в корпус, парирует кунаем", False, False, True, False),
    (10, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (10, 7): (0, 0, "Происходит метание, парирует кунаем", False, False, True, False),
    (10, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (10, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (10, 10): (0, 0, "Противник сбивает сюрикен в воздухе кунаем", False, True, True, False),
    (10, 11): (0, 0, "Происходит метание сюрикена, парирует кунаем", False, False, True, False),
    (10, 12): (0, 0, "Происходит метание сюрикена, парирует кунаем и достает сюрикен", False, False, True, False),

    (11, 1): (-8, 0, None, False, False, False, False),
    (11, 2): (-7, 0, None, False, False, False, False),
    (11, 3): (-8, 0, None, False, False, False, False),
    (11, 4): (-5, 0, None, False, False, False, False),
    (11, 5): (-4, 0, None, False, False, False, False),
    (11, 6): (-5, 0, None, False, False, False, False),
    (11, 7): (0, 0, None, False, False, False, False),
    (11, 8): (-6, 0, None, False, False, False, False),
    (11, 9): (-1, 0, "Подсечка", False, False, False, False),
    (11, 10): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 11): (-8, 0, "Происходит метание куная, кунай попадает в голову", False, True, False, False),
    (11, 12): (0, 0, "Достает кунай, а вторй достает сюрикен", False, False, False, False),

    (12, 1): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 2): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 3): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 4): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 5): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 6): (0, -8, "Происходит метание сюрикена в корпус", False, False, True, False),
    (12, 7): (0, 0, "Парирует кунаем", False, False, True, False),
    (12, 8): (0, -10, "Происходит метание сюрикена в голову", False, False, True, False),
    (12, 9): (-1, 0, "Благодаря подсечке соперник уклоняется от сюрикена", False, False, True, False),
    (12, 10): (0, 0, "Противник сбивает сюрикен в воздухе кунаем", False, True, True, False),
    (12, 11): (0, -10, "Первый игрок метает сюрикен и сбивает атаку кунаем", False, False, True, False),
    (12, 12): (0, -10, "Метает сюрикен, второй игрок достает сюрикен", False, False, True, False)}